### ISSUE TITLE
[Bad credentials] error when creating a new issue

### ISSUE THREAD

**Issue by rokeno** [danhellem/github-actions-issue-to-work-item#118]
I have copied your code into my local repo (due to github conenction limitations in my org) and ran the code and i have found that i get a '`Bad credentials`' when the pipeline runs for the very first time.
If the issue has no label, the pipeline runs twice, one run works, the other one failes, but the ones that fails actually creates the issue:
```
Error in catch statement:
RequestError [HttpError]: Bad credentials
    at /mnt/external1/gha/a01/_work/xxxx-automation/xxxx-automation/.github/actions/github-actions-issue-to-work-item-master/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async updateIssueBody (/mnt/external1/gha/a01/_work/xxxx-automation/xxxx-automation/.github/actions/github-actions-issue-to-work-item-master/index.js:616:18)
    at async main (/mnt/external1/gha/a01/_work/xxxx-automation/xxxx-automation/.github/actions/github-actions-issue-to-work-item-master/index.js:85:38) {
  status: 401,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-length': '80',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 22 Nov [20](https://github.xxxx.com/Azure/xxxx-automation/runs/396965?check_suite_focus=true#step:4:21)[22](https://github.xxxx.com/Azure/xxxx-automation/runs/396965?check_suite_focus=true#step:4:23) 10:[28](https://github.xxxx.com/Azure/xxxx-automation/runs/396965?check_suite_focus=true#step:4:29):36 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=[31](https://github.xxxx.com/Azure/xxxx-automation/runs/396965?check_suite_focus=true#step:4:32)5[36](https://github.xxxx.com/Azure/xxxx-automation/runs/396965?check_suite_focus=true#step:4:37)000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '8B7E:1409:468E0F7:4787455:6[37](https://github.xxxx.com/Azure/sealz-automation/runs/396965?check_suite_focus=true#step:4:38)CA[45](https://github.xxxx.com/Azure/sealz-automation/runs/396965?check_suite_focus=true#step:4:46)4',
    'x-ratelimit-limit': '60',
    'x-ratelimit-remaining': '59',
    'x-ratelimit-reset': '1669116516',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '1',
    'x-xss-protection': '0'
  },
```

When the issue has a label, the pipeline runs 3 times (i believe this was already covered in another open issue on the board).
I had to redact the server name and the project name due to project/Client reasons.

[AB#16156](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/16156)

**Comment by rokeno** [comment]
It's not credentials issue, cause it works and i have seen the items created. I will keep digging. I will also look at the rate limited. Thanks.

**Comment by danhellem** [comment]
@rokeno  ok great. Please let me know if you find the issue is in the code and we can fix.

**Comment by rokeno** [comment]
I've done some digging, looking into index.js, dunno much about java scripts but i have not seen anything there. Oktokit is the one that triggers an authentication issue => 400
All i could find so far is:

```
Date: Tue, 29 Nov 2022 10:45:45 GMT
Server: Kestrel
Transfer-Encoding: chunked
WWW-Authenticate: Bearer
x-tfs-processid: 66239f0a-f1fe-4392-8e81-ce3345d175cc
activityid: d971657f-42cd-4c21-8ce5-9f0dc7c8908c
x-tfs-session: ab1307f0-a33b-45c5-8058-a68f203cfa5e
x-vss-e2eid: 03860721-e323-46fe-b010-2c6e74bdf170
x-vss-senderdeploymentid: c2cd0eb4-8d48-44ab-e222-1c53d7c4a971
x-tfs-serviceerror: The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27+is+not+authorized+to+access+this+resource.
x-vss-s2stargetservice: 0000005A-0000-8888-8000-000000000000/visualstudio.com
X-Frame-Options: DENY

[2022-11-29 10:45:45Z INFO RSAFileKeyManager] Loading RSA key parameters from file /mnt/external1/gha/a01/.credentials_rsaparams
[2022-11-29 10:45:45Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2022-11-29 11:15:46Z INFO MessageListener] No message retrieved from session 'e7bc63f0-be57-4e63-8836-aa8458a5beea' within last 30 minutes.
[2022-11-29 11:40:47Z WARN GitHubActionsService] Authentication failed with status code 401.
```
I don't know what this is: `The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27`

**Comment by danhellem** [comment]
Looks like yo have a bad token or something. Pretty sure it is not action that is a problem.
