### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'html_url')

### ISSUE THREAD

**Issue by dtcMLOps** [danhellem/github-actions-issue-to-work-item#132]
Hi @danhellem ,

I am getting an error, do you know if I am doing something wrong?

```bash
ado_wit: User Story
    ado_new_state: New
    ado_active_state: Active
    ado_close_state: Closed
    ado_bypassrules: true
    log_level: 100
Set values from payload & env
Error in catch statement:
TypeError: Cannot read properties of undefined (reading 'html_url')
    at getValuesFromPayload (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/v2.2/index.js:640:22)
    at main (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/v2.2/index.js:36:12)
    at Object.<anonymous> (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/v2.2/index.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:9[8](https://github.com/ab-inbev-maz/lh-maz-pop/actions/runs/4996466673/jobs/8949682347#step:2:8)1:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:[12](https://github.com/ab-inbev-maz/lh-maz-pop/actions/runs/4996466673/jobs/8949682347#step:2:12))
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:[17](https://github.com/ab-inbev-maz/lh-maz-pop/actions/runs/4996466673/jobs/8949682347#step:2:18):47
Error: TypeError: Cannot read properties of undefined (reading 'html_url')
```

[AB#50990](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/50990)

**Comment by dtcMLOps** [comment]
The problem was that I was testing the action with the push event instead of creating the issue
