### ISSUE TITLE
Error on most of issues

### ISSUE THREAD

**Issue by radiant-alex** [danhellem/github-actions-issue-to-work-item#41]
Added issue and got

`Set values from payload & env
Check to see if work item already exists
Error: Connecting to organization. Check the spelling of the organization name and ensure your token is scoped correctly.
(node:2748) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:66:10)
    at Command.toString (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:60:35)
    at issueCommand (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:23:30)
    at Object.issue (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:27:5)
    at error (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/core.js:127:15)
    at Object.setFailed (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/core.js:101:5)
    at main (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/index.js:108:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Config

name: Sync Issue to Azure DevOps work item

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Sync to Azure
    steps:       
    - uses: danhellem/github-actions-issue-to-work-item@master
      env:     
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: '${{ secrets.ORGANIZATION }}'
        ado_project: 'TestProject'
        ado_wit: 'Product Backlog Item' 
        ado_new_state: 'New'
        ado_close_state: 'Done'
        ado_bypassrules: true

AB#5278

**Comment by danhellem** [comment]
Most likely your organization is not correct or your token is not scoped correctly.
