### ISSUE TITLE
TypeError: (s || "").replace is not a function

### ISSUE THREAD

**Issue by pavelhorak** [danhellem/github-actions-issue-to-work-item#71]
Trying Action in our [workflow](https://github.com/microsoft/vstest/blob/master/.github/workflows/AzureDevOps.yml) and getting following [error](https://github.com/microsoft/vstest/runs/1688612141?check_suite_focus=true):
```
Run danhellem/github-actions-issue-to-work-item@master
Set values from payload & env
Check to see if work item already exists
No work item found, creating work item from issue
(node:2434) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:66:10)
    at Command.toString (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:60:35)
    at issueCommand (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:23:30)
    at Object.issue (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:27:5)
    at error (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/core.js:127:15)
    at Object.setFailed (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/core.js:101:5)
    at main (/home/runner/work/_actions/danhellem/github-actions-issue-to-work-item/master/index.js:116:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2434) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2434) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

[AB#717](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/717)

**Comment by danhellem** [comment]
This is mostly likely caused buy a bad configuration like a bad state, project, work item type. I need to put in some better error handling :(

**Comment by danhellem** [comment]
@pavelhorak find me on MS Teams and we can look at this together. dahellem

**Comment by Msanzdelrio** [comment]
I'm facing the same issue.. Already contacted you in teams :) (masanzde)

**Comment by pavelhorak** [comment]
I found out that at the end action creates Azure DevOps work item, if doesn't exist. It just reports error. However, if work item exists, action updates is just fine and reports no error.

**Comment by pavelhorak** [comment]
I fixed the error in my repo. I opened [PR](https://github.com/danhellem/github-actions-issue-to-work-item/pull/72). I also had to [Authorise personal access token for use with SAML single sign-on](https://docs.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on) for the organisation. 

It'd be worth mentioning it [readme](https://github.com/danhellem/github-actions-issue-to-work-item/edit/master/README.md#L21).

**Comment by danhellem** [comment]
@pavelhorak ok great. I will take a look this week. Thanks for your help

**Comment by pacroy** [comment]
Is this issue already solved? I still face this problem today. As investigated, all work items created since Mar 12 got this issue. Those created before Mar 8 do not have this issue.

The error is the same and the symptom is exactly what @pavelhorak described in https://github.com/danhellem/github-actions-issue-to-work-item/issues/71#issuecomment-761161801

Also, I found that the linkage is not created like before. There usually be a link in the work item and AB#xxxxxx link in the respective GitHub Issue.

**Comment by danhellem** [comment]
The issue is usually because of a invalid token or project name. The linkage works but you need to have the  Azure Boards app installed. it uses that bot to do the linking.

https://github.com/marketplace/azure-boards

**Comment by pacroy** [comment]
@danhellem Thanks for response. I found the root cause now. The account that we use to generate the token does not have `Write` permission to the repo. After add `Write` permission, everything backs working like before. 😄 

PS: Tried with `Read` and `Triage` but didn't work. It must be at least `Write` permission.

**Comment by danhellem** [comment]
@pacroy yeah you need write permissions as it is creating and updating work items. I am pretty sure that is in the readme.md. if not, i will get it updated.

**Comment by matmaly** [comment]
I'm still facing the same issue here. my error message is a bit different though:

```
Run danhellem/github-actions-issue-to-work-item@master
Set values from payload & env
Check to see if work item already exists
No work item found, creating work item from issue
Updating issue body text with AB# syntax
Error in catch statement:
RequestError [HttpError]: Bad credentials
    at /home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async updateIssueBody (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/index.js:613:18)
    at async main (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/index.js:84:38) {
  name: 'HttpError',
  status: 401,
(node:1729239) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '80',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 09 Jul 2021 07:38:27 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    at escapeData (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:66:10)
    server: 'GitHub.com',
    at Command.toString (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:60:35)
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    at issueCommand (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:23:30)
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    at Object.issue (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/command.js:27:5)
    'x-content-type-options': 'nosniff',
    at error (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/core.js:127:15)
    'x-frame-options': 'deny',
    at Object.setFailed (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/node_modules/@actions/core/lib/core.js:101:5)
    'x-github-media-type': 'github.v3; format=json',
    at main (/home/ubuntu/actions-runner/_work/_actions/danhellem/github-actions-issue-to-work-item/master/index.js:138:10)
    'x-github-request-id': 'EE75:02AD:3AE8884:7030F4B:60E7FCF3',
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    'x-ratelimit-limit': '60',
(node:1729239) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

This only happens with new issues, Once the issue is synced it works fine:
![image](https://user-images.githubusercontent.com/15313205/125042658-62aca880-e09a-11eb-9642-68d24bfbde7b.png)

I have write permissions on Github and Read & Write on Work Items on ADO.

Any ideas?
